create database tarefas;
use tarefas;


CREATE TABLE TAREFAS (
    TITULO VARCHAR(255) PRIMARY KEY,
    DESCRICAO TEXT,
    DATA_DE_CRIACAO DATE,
    DATA_DE_VENCIMENTO DATE,
    DATA_CONCLUSAO DATE,
    STATUS ENUM('pendente', 'em andamento', 'concluido'),
    PRIORIDADE ENUM('BAIXA', 'MEDIA', 'ALTA'),
    CATEGORIA ENUM('TRABALHO', 'PESSOAL', 'ESTUDOS', 'OUTROS ASSUNTOS')
);

CREATE TABLE USUARIO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100),
    EMAIL VARCHAR(100) UNIQUE,
    SENHA_HASH TEXT
);